---
- name: Directory created to store temporary files
  file:
    path: '{{ role_path }}/build'
    state: 'directory'

- name: openssl configuration file created
  template:
    src: '{{ role_path }}/templates/openssl-req.cnf.j2'
    dest: '{{ role_path }}/build/openssl-req.cnf'

- name: TLS_DEST_BASENAME set to "selfsigned" if not already overridden
  set_fact:
    TLS_DEST_BASENAME: 'selfsigned'
  when: 'TLS_DEST_BASENAME is undefined'

- name: Self-signed certificate and private key created
  tags: [selfsigned-cert-created]
  command: >
    openssl req
    -config "{{ role_path }}/build/openssl-req.cnf"
    -newkey rsa:2048
    -x509
    -nodes
    -days 3650
    -keyout {{ TLS_PRIVKEY_PATH }}
    -out {{ TLS_CERT_PATH }}
  args:
    creates: '{{ TLS_CERT_PATH }}'

- name: Empty CA chain file created
  tags: [selfsigned-empty-bundle-created]
  file:
    path: '{{ TLS_CACHAIN_PATH }}'
    state: 'touch'
  # The following two lines work around https://github.com/ansible/ansible-modules-core/issues/170
  register: 'touch_log'
  changed_when: 'touch_log.diff.before.state != "file"'

- name: Full certificate chain (same as bare self-signed certificate) created
  tags: [selfsigned-fullchain-created]
  copy:
    src: '{{ TLS_CERT_PATH }}'
    dest: '{{ TLS_CACHAIN_PATH }}'
    remote_src: true
